\hypertarget{classwebsockets_1_1exceptions_1_1_invalid_origin}{}\section{websockets.\+exceptions.\+Invalid\+Origin Class Reference}
\label{classwebsockets_1_1exceptions_1_1_invalid_origin}\index{websockets.\+exceptions.\+Invalid\+Origin@{websockets.\+exceptions.\+Invalid\+Origin}}


Inherits \hyperlink{classwebsockets_1_1exceptions_1_1_invalid_header}{websockets.\+exceptions.\+Invalid\+Header}.

\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{classwebsockets_1_1exceptions_1_1_invalid_origin_a32b7316759b6e3db33a7e61e42afad85}\label{classwebsockets_1_1exceptions_1_1_invalid_origin_a32b7316759b6e3db33a7e61e42afad85}} 
def {\bfseries \+\_\+\+\_\+init\+\_\+\+\_\+} (self, origin)
\end{DoxyCompactItemize}


\subsection{Detailed Description}
\begin{DoxyVerb}Exception raised when the Origin header in a request isn't allowed.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+6/site-\/packages/websockets/exceptions.\+py\end{DoxyCompactItemize}
